name: "Podcast Generator"
author: "Alberto Dominguez"
description: "Generates a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding: 
  icon: "git-branch"
  color: "red"
inputs: 
  email:
    description: The committer's email address
    required: true
    default: ${{ github.actor }}@locallhost
  name:
    description: The committer's name
    required: true
    default: ${{ github.actor }}